# spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/videohost_db}
# server.port=${PORT:8081}

spring.data.mongodb.uri=mongodb+srv://anna_hanzhuha:anna_hanzhuha@cluster0.oqpae1u.mongodb.net/videohost_db
server.port=8081